### ISSUE TITLE
Broke during mod loading

### ISSUE THREAD

**Issue by MissLexterPhD** [AdityaGupta1/eloncraft#141]
[crash-2019-08-02_19.44.01-client.txt](https://github.com/AdityaGupta1/eloncraft/files/3463332/crash-2019-08-02_19.44.01-client.txt)

**Comment by AdityaGupta1** [comment]
Forge version is very old, try [recommended](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-installer.jar) or [latest](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2838/forge-1.12.2-14.23.5.2838-installer.jar)

**Comment by MissLexterPhD** [comment]
works after installing recommended
